#!/bin/sh
#
# sshd        Starts sshd.
#

# Make sure the ssh-keygen progam exists
umask 077

start() 
{
	mount devpts /dev/pts -t devpts
	mknod /dev/kvm c 10 232
	chmod a+rw /dev/kvm
	/usr/bin/qemu.sh /bzImage qboot.bin
}
stop() {
	pkill qemu
	echo "OK"
}
restart() {
	stop
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

