QBOOT_VERSION = a5300c4949b8d4de2d34bedfaed66793f48ec948
QBOOT_SITE = $(call github,bonzini,qboot,$(QBOOT_VERSION))

QBOOT_INSTALL_STAGING = YES


QBOOT_POST_INSTALL_TARGET_HOOKS += QBOOT_INSTALL_SCRIPTS
QBOOT_POST_INSTALL_TARGET_HOOKS += QBOOT_INSTALL_SCRIPTS2

$(eval $(meson-package))
